# -*- coding: utf-8 -*-
"""Social Media Engagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnmKR_nIrSrWGcqVH3-iYSSPNJ68iDCL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Loading and Exploration of the Dataset"""

#Loading the Dataset
df = pd.read_csv("social_media_engagement_dataset.csv")
print(df.shape)
print(df.info())
print(df.isnull().sum())
print(df.describe())

"""Correlation Analysis"""

numeric_cols = [
    'post_length',
    'views',
    'likes',
    'comments',
    'shares',
    'engagement_rate'
]

corr_matrix = df[numeric_cols].corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix,
            annot=True,
            cmap='coolwarm',
            fmt='.2f')

plt.title('Correlation Matrix')
plt.show()

"""Exploratory Visulaizations"""

# Posts by Platform
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='platform')
plt.title('Number of Posts by Platform')
plt.xticks(rotation=45)
plt.show()

# Posts by Content Type
plt.figure(figsize=(6,5))
sns.countplot(data=df, x='post_type')
plt.title('Number of Posts by Type')
plt.show()

# Average Engagement Rate by Platform
platform_engagement = df.groupby('platform')['engagement_rate'].mean().sort_values()

plt.figure(figsize=(8,5))
platform_engagement.plot(kind='bar')
plt.title('Average Engagement Rate by Platform')
plt.ylabel('Engagement Rate')
plt.show()

# Average Engagement Rate by Post Type
post_engagement = df.groupby('post_type')['engagement_rate'].mean().sort_values()

plt.figure(figsize=(6,5))
post_engagement.plot(kind='bar')
plt.title('Average Engagement Rate by Post Type')
plt.ylabel('Engagement Rate')
plt.show()

"""Outlier Analysis"""

numeric_cols = [
    'post_length',
    'views',
    'likes',
    'comments',
    'shares',
    'engagement_rate'
]

plt.figure(figsize=(15,8))

for i, col in enumerate(numeric_cols, 1):
    plt.subplot(2,3,i)
    sns.boxplot(y=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

"""Feature Scaling"""

from sklearn.preprocessing import StandardScaler

features = [
    'post_length',
    'views',
    'likes',
    'comments',
    'shares',
    'engagement_rate'
]

X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

"""Optimal Number of Clusters
(Elbow Method)
"""

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []

K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K_range, inertia, marker='o')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal K')
plt.grid(True)
plt.show()

"""Adding the Silhouette Score to make it Strong"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

for k in range(2, 7):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(X_scaled, labels)

    print(f"K={k}, Silhouette Score={score:.4f}")

"""K-Means Model"""

from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=4,
    random_state=42,
    n_init=10
)

df['kmeans_cluster'] = kmeans.fit_predict(X_scaled)

df['kmeans_cluster'].value_counts().sort_index()

# Profiling the Clusters
cluster_profile = df.groupby('kmeans_cluster')[
    [
        'post_length',
        'views',
        'likes',
        'comments',
        'shares',
        'engagement_rate'
    ]
].mean()

print(cluster_profile)

"""Visualizing the Clusters (PCA)"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))

scatter = plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=df['kmeans_cluster'],
    cmap='viridis',
    alpha=0.6
)

plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('K-Means Cluster Visualization')

plt.colorbar(scatter)
plt.show()

"""Obatining the Final K-Means"""

from sklearn.metrics import silhouette_score

kmeans_score = silhouette_score(
    X_scaled,
    df['kmeans_cluster']
)

print("K-Means Silhouette Score:", round(kmeans_score,4))

"""DBSCAN"""

from sklearn.neighbors import NearestNeighbors
import numpy as np
import matplotlib.pyplot as plt

neighbors = NearestNeighbors(n_neighbors=5)

neighbors_fit = neighbors.fit(X_scaled)

distances, indices = neighbors_fit.kneighbors(X_scaled)

distances = np.sort(distances[:,4])

plt.figure(figsize=(8,5))
plt.plot(distances)
plt.title('K-Distance Graph for DBSCAN')
plt.xlabel('Data Points')
plt.ylabel('5th Nearest Neighbor Distance')
plt.grid(True)
plt.show()

# Fitting the DBSCAN
from sklearn.cluster import DBSCAN
import pandas as pd

dbscan = DBSCAN(
    eps=0.75,
    min_samples=5
)

df['dbscan_cluster'] = dbscan.fit_predict(X_scaled)

print(df['dbscan_cluster'].value_counts().sort_index())

noise_points = (df['dbscan_cluster'] == -1).sum()

noise_percentage = (noise_points / len(df)) * 100

print("Noise Points:", noise_points)
print("Noise Percentage:", round(noise_percentage,2), "%")

"""DBSCAN Visualization"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

X_pca = PCA(n_components=2).fit_transform(X_scaled)

plt.figure(figsize=(8,6))

scatter = plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=df['dbscan_cluster'],
    cmap='viridis',
    alpha=0.6
)

plt.title('DBSCAN Cluster Visualization')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')

plt.colorbar(scatter)

plt.show()